---
title: "hunterdickey_A9"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: fill
---

```{r global, include=FALSE}
library(shiny)
library(flexdashboard)
library(tidyverse)
library(leaflet)
library(sf)
library(plotly)
library(rsconnect)

bay_zips <- readRDS("bay_zips.rds")

pge_data_raw <- readRDS("pge_data_raw.rds")

pge_data <-
  pge_data_raw %>% 
  filter(
    CUSTOMERCLASS %in% c(
      "Elec- Commercial",
      "Elec- Residential",
      "Gas- Commercial",
      "Gas- Residential"
    )
  ) %>% 
  group_by(
    MONTH, 
    YEAR, 
    CUSTOMERCLASS
  ) %>% 
  summarize(
    TOTALKBTU = sum(TOTALKBTU, na.rm = T)
  ) %>% 
  mutate(
    DATE = 
      paste(
        YEAR,
        MONTH, 
        "01",
        sep="-"
      ) %>% as.Date()
  )
```
Inputs {.sidebar}
-------------------------------------

```{r}
checkboxGroupInput(
  inputId = "year",
  label = "Year: ",
  choices = 2017:2020,
  selected = 2020
)

selectInput(
  inputId = "class",
  label = "Class: ",
  choices = c("Elec- Commercial","Elec- Residential","Gas- Commercial", "Gas- Residential")
)
```
Column
-------------------------------------

### Monthly consumption

```{r} 
#what is displaying
plotlyOutput("plot")
```


```{r, context = "server"}

observeEvent({
  input$year
  input$class
  }, {
  
  chart <- pge_data %>% 
  filter(
    CUSTOMERCLASS %in% input$class,
    YEAR %in% input$year
  ) %>% 
  ggplot(
    aes(
      x = MONTH,
      y = TOTALKBTU/1e9
    )
  ) +
  geom_line(
    aes(
      color = YEAR %>% factor()
    )
  ) +
  scale_x_discrete(
    limits = c(
      "Jan",
      "Feb",
      "Mar",
      "Apr",
      "May",
      "Jun",
      "Jul",
      "Aug",
      "Sep",
      "Oct",
      "Nov",
      "Dec"
    )
  ) +
  labs(
    x = "",
    y = "Total kBTUs (billions)",
    title = paste0("Bay Area ",input$class," Energy Consumption (kBTU), "),
    color = "Year"
  ) + 
  theme(legend.position = "top right")

output$plot <- renderPlotly({
  chart %>% 
   ggplotly() %>% 
    config(displayModeBar = F)
  })
})

```

Column
-------------------------------------

### ZCTA consumption

```{r}
leafletOutput("map")
```


```{r}

observeEvent({
  input$year
  input$class
  }, {
  #ch 2.1
pge_20_res_elec <-
  pge_data_raw %>% 
  filter(
    CUSTOMERCLASS %in% input$class,
    YEAR == max(input$year)
  ) %>% 
  mutate(
    ZIPCODE = ZIPCODE %>% as.character()
  ) %>% 
  group_by(ZIPCODE) %>% 
  summarize(
    TOTALKBTU = sum(TOTALKBTU, na.rm = T)
  ) %>% 
  right_join(
    bay_zips %>% select(GEOID10),
    by = c("ZIPCODE" = "GEOID10")
  ) %>% 
  st_as_sf() %>% 
  st_transform(4326)

res_pal <- colorNumeric(
  palette = "Reds",
  domain = 
    pge_20_res_elec$TOTALKBTU
)

output$map <- renderLeaflet({
  
leaflet() %>% 
  addProviderTiles(provider = providers$CartoDB.Positron) %>% 
  addPolygons(
    data = pge_20_res_elec,
    fillColor = ~res_pal(TOTALKBTU),
    color = "white",
    opacity = 0.5,
    fillOpacity = 0.5,
    weight = 1,
    label = ~paste0(
      round(TOTALKBTU), 
      " kBTU total in ",
      ZIPCODE
    ),
    highlightOptions = highlightOptions(
      weight = 2,
      opacity = 1
    )
  ) %>% 
  addLegend(
    data = pge_20_res_elec,
    pal = res_pal,
    values = ~TOTALKBTU,
    title = paste0("Total Bay Area ",input$class," Energy Consumption(kBTU) , ",  max(input$year)))
  })
})

```
