---
title: "hunterdickey_A8"
author: "Hunter Dickey"
date: "11/16/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)
```


Treated:time is the "difference-in-differences" result and is statistically significant with a p-value of .017. The addition of the Antioch BART appears to have contributed 967.52 new BART commuters. 
```{r}
library(tidyverse)
library(censusapi)
library(StatMatch)
library(leaflet)
library(sf)
library(tigris)

Sys.setenv(CENSUS_KEY="c8aa67e4086b4b5ce3a8717f59faa9a28f611dab")

acs_vars_2019_5yr <-
  listCensusMetadata(
    name = "2019/acs/acs5",
    type = "variables"
  )

bay_county_names <-
  c(
    "Alameda",
    "Contra Costa",
    "Marin",
    "Napa",
    "San Francisco",
    "San Mateo",
    "Santa Clara",
    "Solano",
    "Sonoma"
  )
ca_pumas <-
  pumas("CA", cb = T, progress_bar = F)

bay_counties <-
  counties("CA", cb = T, progress_bar = F) %>%
  filter(NAME %in% bay_county_names)

bay_pumas <-
  ca_pumas %>% 
  st_centroid() %>% 
  .[bay_counties, ] %>% 
  st_drop_geometry() %>% 
  left_join(ca_pumas %>% select(GEOID10)) %>% 
  st_as_sf()
```

```{r}
leaflet() %>% 
  addProviderTiles(providers$CartoDB.Positron) %>% 
  addPolygons(
    data = bay_pumas,
    weight = 1,
    color = "gray",
    label = ~PUMACE10
  ) %>% 
  addMarkers(
    lng = -121.78024807811298,
    lat = 37.99579695455122
  ) %>% 
  addPolygons(
    data = bay_pumas %>% 
      filter(PUMACE10 == "01309")
  )
```

```{r}
# pums_2014_2019 <-
#   2014:2019 %>% 
#   map_dfr(function(year){
#     
#     getCensus(
#       name = "acs/acs1/pums",
#       vintage = year,
#       region = "public use microdata area:*", 
#       regionin = "state:06",
#       vars = c(
#         "SERIALNO",
#         "SPORDER",
#         ifelse(
#           year == 2019,
#           "JWTRNS",
#           "JWTR"
#         ),
#         "PWGTP",
#         paste0("PWGTP",1:80)
#       )
#     ) %>% 
#       mutate(
#         year = year,
#         PUMA = public_use_microdata_area %>% str_pad(5,"left","0")
#       ) %>% 
#       filter(
#         PUMA %in% bay_pumas$PUMACE10
#       ) %>% 
#       rename(
#         JWTR = ifelse(
#           year == 2019,
#           "JWTRNS",
#           "JWTR"
#         )
#       )
#     
#   })

pums_2014_2019 <- readRDS("pums_2014_2019_wts.rds")

pums_bart <- pums_2014_2019 %>%
  mutate(
    PWGTP = as.numeric(PWGTP),
    bart = ifelse(
      JWTR %in% c("4"),
      PWGTP,
      0
    )
  ) %>% 
  group_by(PUMA, year) %>% 
  summarize(
    pop = sum(PWGTP),
    bart = sum(bart)
  )
```

```{r}
pums_pal <- colorNumeric(
  palette = "YlOrRd",
  domain = pums_bart %>% 
    filter(year == 2017) %>% 
    pull(pop)
)

leaflet() %>% 
  addProviderTiles(providers$CartoDB.Positron) %>% 
  addPolygons(
    data = pums_bart %>% 
      filter(year == 2017) %>% 
      right_join(bay_pumas %>% select(PUMA = PUMACE10)) %>% 
      st_as_sf(),
    fillColor = ~pums_pal(pop),
    color = "white",
    weight = 1,
    fillOpacity = 0.5,
    label = ~paste0(PUMA,": Population ", pop)
  )
```

```{r}
pums_pal <- colorNumeric(
  palette = "GnBu",
  domain = pums_bart %>% 
    filter(year == 2017) %>% 
    pull(bart)
)

leaflet() %>% 
  addProviderTiles(providers$CartoDB.Positron) %>% 
  addPolygons(
    data = pums_bart %>% 
      filter(year == 2017) %>% 
      right_join(bay_pumas %>% select(PUMA = PUMACE10)) %>% 
      st_as_sf(),
    fillColor = ~pums_pal(bart),
    color = "white",
    weight = 1,
    fillOpacity = 0.5,
    label = ~paste0(PUMA,": ", bart, " BART commute riders")
  )
```


```{r}


```

```{r}
#clean 
pums_bart_clean <-
  pums_bart %>% 
  select(-pop) %>% 
  pivot_wider(
    names_from = year,
    values_from = bart
  )
```

```{r}
obs_matrix <-
  pums_bart_clean %>% 
  ungroup() %>% 
  select(`2014`,`2015`,`2016`) %>% 
  as.matrix()

dist_matrix <- mahalanobis.dist(obs_matrix)

rownames(dist_matrix) <- pums_bart_clean$PUMA
colnames(dist_matrix) <- pums_bart_clean$PUMA

match <- dist_matrix["01309",] %>% 
  as.data.frame() %>% 
  rownames_to_column() %>% 
  rename(
    PUMA = rowname,
    match = "."
  ) %>% 
  right_join(
    pums_bart_clean
  ) %>% 
  arrange(match) %>% 
  .[1:11, ] %>% 
  left_join(bay_pumas %>% select(PUMA = PUMACE10)) %>% 
  st_as_sf()
```

```{r}
leaflet() %>% 
  addTiles() %>% 
  addProviderTiles(providers$CartoDB.Positron) %>% 
  addPolygons(
    data = match[1, ],
    color = "red",
    label = ~PUMA
  ) %>% 
  addPolygons(
    data = match[-1, ],
    label = ~PUMA
  )
```

```{r}
match_pumas <-
  match %>% 
  filter(!PUMA %in% c("01309")) %>% 
  st_drop_geometry() %>% 
  select(-match) %>% 
  pivot_longer(
    -PUMA,
    names_to = "year",
    values_to = "bart"
  ) %>%
  group_by(
    year
  ) %>% 
  summarize(
    bart = mean(bart),
    PUMA = "Similar PUMAs"
  )

treatment_pumas <-
  match %>% 
  filter(PUMA %in% c("01309")) %>% 
  select(-match) %>% 
  st_drop_geometry() %>% 
  pivot_longer(
    -PUMA,
    names_to = "year",
    values_to = "bart"
  )

rbind(
  treatment_pumas,
  match_pumas
) %>% 
  ggplot(
    aes(
      x = as.numeric(year),
      y = bart,
      color = PUMA
    )
  ) +
  geom_line() +
  geom_vline(xintercept = 2018, linetype = "dashed") +
  labs(
    title = "Antioch vs. control neighborhoods, BART ridership",
    x = "Year",
    y = "BART commute riders"
  )

```

```{r}
transit_did <-
  match %>% 
  st_drop_geometry() %>% 
  select(-match) %>% 
  pivot_longer(
    -PUMA,
    names_to = "year",
    values_to = "bart"
  ) %>% 
  mutate(
    year = year %>% as.numeric(),
    time = ifelse(year >= 2018, 1, 0),
    treated = ifelse(PUMA == "01309", 1, 0)
  )

did_reg <- lm(bart ~ treated*time, data = transit_did)

summary(did_reg)
```

