---
title: "Dashboard Demo-in class work"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: fill
---
*this version of shinyhub shows how i connected the account and how i got to bay counties 

*runtime shiny is about running code 
```{r}
rsconnect::setAccountInfo(name='hunterdickey', token='F394A5EE4F02DBF20BD1ADA3824DA24F', secret='WxmILdUZiBgcRQT5NG5FCk+lWKX8wa1WT7V2mpuQ')

```


```{r global, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(leaflet)
library(sf)
library(plotly)
library(rsconnect)
library(tigris)

 ca_zips <-zctas("CA")

 bay_county_names <-
   c(
     "Alameda",
     "Contra Costa",
     "Marin",
     "Napa",
     "San Francisco",
     "San Mateo",
     "Santa Clara",
     "Solano",
     "Sonoma"
   )

 bay_counties <- counties("CA") %>% filter(NAME %in% bay_county_names)

bay_zips <- ca_zips[bay_counties,]

saveRDS(bay_zips, "bay_zips.rds")

bay_zips <- readRDS("bay_zips.rds")

pge_data_raw <- readRDS("pge_data_raw.rds")

pge_data <-
  pge_data_raw %>% 
  filter(
    CUSTOMERCLASS %in% c(
      "Elec- Commercial",
      "Elec- Residential",
      "Gas- Commercial",
      "Gas- Residential"
    )
  ) %>% 
  group_by(
    MONTH, 
    YEAR, 
    CUSTOMERCLASS
  ) %>% 
  summarize(
    TOTALKBTU = sum(TOTALKBTU, na.rm = T)
  ) %>% 
  mutate(
    DATE = 
      paste(
        YEAR,
        MONTH, 
        "01",
        sep="-"
      ) %>% as.Date()
  )
```

Column
-------------------------------------

### Monthly consumption (each triple hastag can only output one thing, so be good about what you put-- intentional-- if not it will outout just the last thing)

```{r}
chart <- pge_data %>% 
  filter(
    CUSTOMERCLASS %in% c(
      "Elec- Residential"
    ),
    YEAR == 2020 #make multiple, aes is ready for it 
  ) %>% 
  ggplot(
    aes(
      x = MONTH,
      y = TOTALKBTU/1e9
    )
  ) +
  geom_line(
    aes(
      color = YEAR %>% factor()
    )
  ) +
  scale_x_discrete(
    limits = c(
      "Jan",
      "Feb",
      "Mar",
      "Apr",
      "May",
      "Jun",
      "Jul",
      "Aug",
      "Sep",
      "Oct",
      "Nov",
      "Dec"
    )
  ) +
  labs(
    x = "",
    y = "Total kBTUs (billions)",
    title = "Residential Energy Consumption in the Bay Area, 2020",
    color = "Year"
  ) + 
  theme(legend.position = "none")

chart %>% 
  ggplotly() %>% 
  config(displayModeBar = F)
```

Column
-------------------------------------

### ZCTA consumption

```{r}

#ch 2.1
pge_20_res_elec <-
  pge_data_raw %>% 
  filter(
    CUSTOMERCLASS == "Elec- Residential",
    YEAR == 2020
  ) %>% 
  mutate(
    ZIPCODE = ZIPCODE %>% as.character()
  ) %>% 
  group_by(ZIPCODE) %>% 
  summarize(
    TOTALKBTU = sum(TOTALKBTU, na.rm = T)
  ) %>% 
  right_join(
    bay_zips %>% select(GEOID10),
    by = c("ZIPCODE" = "GEOID10")
  ) %>% 
  st_as_sf() %>% 
  st_transform(4326)

res_pal <- colorNumeric(
  palette = "Reds",
  domain = 
    pge_20_res_elec$TOTALKBTU
)

leaflet() %>% 
  addProviderTiles(provider = providers$CartoDB.Positron) %>% 
  addPolygons(
    data = pge_20_res_elec,
    fillColor = ~res_pal(TOTALKBTU),
    color = "white",
    opacity = 0.5,
    fillOpacity = 0.5,
    weight = 1,
    label = ~paste0(
      round(TOTALKBTU), 
      " kBTU total in ",
      ZIPCODE
    ),
    highlightOptions = highlightOptions(
      weight = 2,
      opacity = 1
    )
  ) %>% 
  addLegend(
    data = pge_20_res_elec,
    pal = res_pal,
    values = ~TOTALKBTU,
    title = "Total Residential<br>Electricity (kBTU), 2020"
  )
```