---
title: "Week 7-Example"
author: "Hunter Dickey"
date: "11/7/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(censusapi)
library(sf)
library(dplyr)
library(mapview)
library(tigris)
library(readxl)
library(spdep)
library(spatialreg)
library(survey)
library(leaflet)
getwd()

Sys.setenv(CENSUS_KEY="c8aa67e4086b4b5ce3a8717f59faa9a28f611dab")
```

```{r}

temp <- tempfile()
download.file("https://www2.census.gov/programs-surveys/acs/data/pums/2019/1-Year/csv_hca.zip",destfile = temp)

pums_hca_2019_1yr <- read_csv("psam_h06.csv")













# pums_hca_2019_1yr <- getCensus(
#     name = "acs/acs1/pums",
#     vintage = 2019,
#     region = "public use microdata area:*",
#     regionin = "state:06",
#     vars = c(
#      "SERIALNO",
#       "SPORDER",
#       "PWGTP",
#       "WGTP",
#       "YBL",
#       "BLD",
#       "TEN",
#       "MV",
#       "HINCP",
#       "AGEP"
#     )
#   )
```

```{r}
# saveRDS(pums_hca_2019_1yr, "a6_pums_hca.rds")
# 
# pums_hca_2019_1yr <- readRDS("a6_pums_hca.rds")

library(tigris)
library(sf)
library(tidyverse)
library(mapview)
library(readxl)
library(spdep)
library(spatialreg)
library(survey)

sf_boundary <-
  counties("CA", cb = T, progress_bar = F) %>%
  filter(NAME == "San Francisco")

ca_pumas <-
  pumas("CA", cb = T, progress_bar = F)

sf_pumas <-
  ca_pumas %>% 
  st_centroid() %>% 
  .[sf_boundary, ] %>% 
  st_set_geometry(NULL) %>% 
  left_join(ca_pumas %>% select(GEOID10)) %>% 
  st_as_sf()

```

```{r}
data <- pums_hca_2019_1yr %>% 
  filter(PUMA %in% sf_pumas$PUMACE10) %>% 
  mutate(
    HINCP = as.numeric(HINCP),
    TEN = factor(TEN),
    MV = factor(MV)
  ) %>% 
  select(
    HINCP,
    TEN,
    MV,
    starts_with("WGTP")
  ) %>% 
  filter_all(all_vars(!is.na(.)))
```

```{r}

data$WGTP <- as.numeric(data$WGTP)

design <- svrepdesign(
  data = data,
  type = "ACS",
  repweights = data[ , 5:84],
  weights = ~WGTP
)


# test <- repweights = data[5:84, ]

class(data$WGTP)

model  <- svyglm(
  formula = HINCP ~ TEN + MV,
  family = gaussian(),
  design = design
)

summary(model)

weighted_model <- data %>%
  lm(
    formula = HINCP ~ TEN + MV, 
    data = ., 
    weights = WGTP
  )

summary(weighted_model)
#get completely different standard error
# usually smaller 
# estimates are correct but SEs are off 
# https://www.census.gov/content/dam/Census/library/publications/2021/acs/acs_pums_handbook_2021.pdf 

#equity analysis was looping 
# if you gotta do something like 80 times, set yourself up to do so 
replicates_model <- 
  1:80 %>%
  map_dfr(function(x) {
    
    data %>%
      rename(replicate = paste0("WGTP", x))%>%
      lm(
        formula = HINCP ~ TEN + MV,
        data =.,
        weights = replicate 
      ) %>%
      .$coefficients %>%
      as.data.frame() %>%
      rownames_to_column()
    
  })

weighted_model_summary <- replicates_model %>% 
  rename(replicate = ".") %>% 
  left_join(
    weighted_model$coefficients %>% 
      as.data.frame() %>% 
      rownames_to_column() %>% 
      rename(base = ".")
  ) %>% 
  group_by(rowname) %>% 
  summarize(
    stderr = sqrt(4/80*sum((base-replicate)^2))
  )
```

