---
title: "Assignment 1"
author: "Hunter Dickey"
date: "9/27/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)


```

## R Markdown
```{r}
rm(list=ls())
library(tidyverse)
setwd("~/Documents/GitHub/Assignment-1")
pge_data <- read_csv("https://pge-energydatarequest.com/public_datasets")

pge_20_q1_elec <- read_csv("PGE_2020_Q1_ElectricUsageByZip.csv")


```

```{r}
library(tidyverse)

years <- 2017:2020
quarters <- 1:4
type <- "Electric"

pge_1720_elec <- NULL
for(year in years) {
  for(quarter in quarters) {
  
  filename <- 
    paste0(
      "PGE_",
      year,
      "_Q",
      quarter,
      "_",
      type,
      "UsageByZip.csv"
    )
  print(filename)
  
  temp <- read_csv(filename)
  
  pge_1720_elec <- rbind(pge_1720_elec,temp)
  # 

  saveRDS(pge_1720_elec, "pge_1720_elec.rds")
  }
}

class(pge_1720_elec$TOTALKWH)
# adding 2021 Q1 and Q2


```


```{r}
year <- 2021
quarters <- 1:2
type <- "Electric"

pge_21_electric <- NULL
  for(quarter in quarters) {
  filename <- 
    paste0(
      "PGE_",
      year,
      "_Q",
      quarter,
      "_",
      type,
      "UsageByZip.csv"
    )
  print(filename)
  
  temp <- read_csv(filename)
  
  pge_21_electric <- rbind(pge_21_electric,temp)
  # 

  saveRDS(pge_21_electric, "pge_21_electric.rds")
}

class(pge_21_electric$TOTALKWH)

class(pge_1720_elec$TOTALKWH)

pge_elec_total <- rbind(pge_1720_elec, pge_21_electric)

class(pge_elec_total$TOTALKWH)
```



```{r}
library(tidyverse)

years <- 2017:2021
quarters <- 1:4
type <- "Gas"

pge_1720_gas <- NULL
for(year in years) {
  for(quarter in quarters) {
  filename <- 
    paste0(
      "PGE_",
      year,
      "_Q",
      quarter,
      "_",
      type,
      "UsageByZip.csv"
    )
  print(filename)
  
  temp <- read_csv(filename)
  
  pge_1720_gas <- rbind(pge_1720_gas,temp)
  # 

  saveRDS(pge_1720_gas, "pge_1720_gas.rds")
  }
}
# adding 2021 Q1 and Q2


year <- 2021
quarters <- 1:2
type <- "Gas"

pge_21_gas <- NULL
  for(quarter in quarters) {
  filename <- 
    paste0(
      "PGE_",
      year,
      "_Q",
      quarter,
      "_",
      type,
      "UsageByZip.csv"
    )
  print(filename)
  
  temp <- read_csv(filename)
  
  pge_21_gas <- rbind(pge_21_gas,temp)
  # 

  saveRDS(pge_21_gas, "pge_21_gas.rds")
}



pge_gas_total <- rbind(pge_1720_gas, pge_21_gas)

class(pge_gas_total$TOTALTHM)

```

```{r}
#Conversions
library(tidyverse)
#KWH to KBTU
pge_elec_total$TOTALKBTU <- pge_elec_total$TOTALKWH *  3.412
#Therms to KBTUs
pge_gas_total$TOTALKBTU <- pge_gas_total$TOTALTHM * 99976.1


```


```{r}
#Plots

library(tidyverse)
library(plotly)


#Electric 
unique(pge_elec_total$CUSTOMERCLASS)
res_elec <- pge_elec_total[(pge_elec_total$CUSTOMERCLASS=="Elec- Residential"), na.rm = TRUE]

com_elec <- pge_elec_total[which(pge_elec_total$CUSTOMERCLASS=="Elec- Commercial"), na.rm = TRUE]

#Gas

res_gas <- pge_gas_total[which(pge_elec_total$CUSTOMERCLASS=="Gas- Residential"), na.rm = TRUE]

com_gas <- pge_gas_total[which(pge_elec_total$CUSTOMERCLASS=="Gas- Commercial"), na.rm = TRUE]


#combine

res_data <- rbind(res_elec, res_gas)
  
com_data <- rbind(com_elec, com_gas)
```

```{r}
library(tidyverse)
library(plotly)
pge_chart_commercial <-
 com_data %>% 
  ggplot() +
  geom_bar(
    aes(
      x = MONTH,
      y = TOTALKBTU,
      fill = CUSTOMERCLASS
    ),
    stat = "identity",
    position = "stack"
  ) +
  labs(
    x = "Month",
    y = "KBTU",
    title = "PG&E Territory Monthly Commercial Usage",
    fill = "Electricity Type"
  )
pge_chart_commercial %>% 
  ggplotly() %>% 
  layout(
    xaxis = list(fixedrange = T),
    yaxis = list(fixedrange = T)
  ) %>% 
  config(displayModeBar = F)

```

```{r}
library(tidyverse)
library(plotly)
pge_chart_res <-
 res_data %>% 
  ggplot() +
  geom_bar(
    aes(
      x = MONTH,
      y = TOTALKBTU,
      fill = CUSTOMERCLASS
    ),
    stat = "identity",
    position = "stack"
  ) +
  labs(
    x = "Month",
    y = "KBTU",
    title = "PG&E Territory Monthly Residential Usage",
    fill = "Electricity Type"
  )
pge_chart_res %>% 
  ggplotly() %>% 
  layout(
    xaxis = list(fixedrange = T),
    yaxis = list(fixedrange = T)
  ) %>% 
  config(displayModeBar = F)
```

